load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "WidgetsLib",
    module_name = "WidgetsLib",

    srcs = glob(["Sources/*.swift"]),
    visibility = ["//visibility:public"],
)
