load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "Swinject",
    srcs = glob(["Sources/*.swift"]),
    module_name = 'Swinject',

    visibility = ["//visibility:public"],
)
