load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "SegementedControl",
    srcs = glob(["Sources/**/*.swift"]),
    module_name = 'SegementedControl',
    visibility = ["//visibility:public"],
)
