name: build

on: [push, pull_request]

jobs:
  run-test:
    runs-on: self-hosted
    continue-on-error: true
    strategy:
      matrix:
        destination: [
          'macOS', 
          'iOS Simulator,name=iPhone 15', 
          'tvOS Simulator,name=Apple TV', 
          'watchOS Simulator,name=Apple Watch Series 8 (41mm)'
        ]
        xcode: [
          '15.3',
          '15.4'
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Install Gems
        run: bundle install
      - name: Run tests
        env:
          DESTINATION: platform=${{ matrix.destination }}
          XCODE_VERSION: ${{ matrix.xcode }}
        run: bundle exec fastlane test_ci
